# Generated by Django 6.0.1 on 2026-02-14 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_media_height_media_order_idx_media_width_like_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='url',
        ),
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.ImageField(default='', upload_to='post_photos/'),
            preserve_default=False,
        ),
    ]
