# Generated by Django 6.0.1 on 2026-02-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_media_url_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='post_media/'),
        ),
    ]
