# Generated by Django 6.0.1 on 2026-03-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_note_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='file',
            field=models.URLField(max_length=512),
        ),
    ]
